SRC = $(wildcard *.c)

all:$(SRC:.c=.o)
	gcc hw0101.c -o hw0101
	gcc hw0102.c -o hw0102
	gcc hw0103.c mystring.o -o hw0103
	gcc hw0104.o mystring.o -o hw0104 
	gcc hw0105.c mysplit.o -o hw0105
	gcc hw0106.c -o hw0106
